// <auto-generated />
using System;
using LittleShipManagementSystemData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LittleShipManagementSystemData.Migrations
{
    [DbContext(typeof(LittleShipManagementContext))]
    [Migration("20230728073753_CreateInitialDb")]
    partial class CreateInitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JourneyWorker", b =>
                {
                    b.Property<int>("JourneysId")
                        .HasColumnType("int");

                    b.Property<int>("WorkersId")
                        .HasColumnType("int");

                    b.HasKey("JourneysId", "WorkersId");

                    b.HasIndex("WorkersId");

                    b.ToTable("JourneyWorker");
                });

            modelBuilder.Entity("ListtleShipManagementSystemDomain.Entities.Captain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnTheWay")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Captain", (string)null);
                });

            modelBuilder.Entity("ListtleShipManagementSystemDomain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Company", (string)null);
                });

            modelBuilder.Entity("ListtleShipManagementSystemDomain.Entities.Container", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContainerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LoadId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("LoadType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeightAmount")
                        .HasColumnType("int");

                    b.Property<string>("WeightType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LoadId");

                    b.ToTable("Container", (string)null);
                });

            modelBuilder.Entity("ListtleShipManagementSystemDomain.Entities.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerCompanyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsContractCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("JourneyId")
                        .HasColumnType("int");

                    b.Property<int>("LoadId")
                        .HasColumnType("int");

                    b.Property<int>("ShipLogisticCompanyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerCompanyId");

                    b.HasIndex("JourneyId")
                        .IsUnique();

                    b.HasIndex("LoadId")
                        .IsUnique();

                    b.HasIndex("ShipLogisticCompanyId");

                    b.ToTable("Contract", (string)null);
                });

            modelBuilder.Entity("ListtleShipManagementSystemDomain.Entities.Dock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dock", (string)null);
                });

            modelBuilder.Entity("ListtleShipManagementSystemDomain.Entities.Journey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaptainId")
                        .HasColumnType("int");

                    b.Property<int>("EndDockId")
                        .HasColumnType("int");

                    b.Property<string>("GuessedJourneyTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ShipId")
                        .HasColumnType("int");

                    b.Property<int>("StartDockId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CaptainId");

                    b.HasIndex("EndDockId");

                    b.HasIndex("ShipId");

                    b.HasIndex("StartDockId");

                    b.ToTable("Journey", (string)null);
                });

            modelBuilder.Entity("ListtleShipManagementSystemDomain.Entities.Load", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Load", (string)null);
                });

            modelBuilder.Entity("ListtleShipManagementSystemDomain.Entities.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId1")
                        .HasColumnType("int");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("JourneyId")
                        .HasColumnType("int");

                    b.Property<int?>("LoadId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyId1");

                    b.HasIndex("ContractId")
                        .IsUnique();

                    b.HasIndex("JourneyId");

                    b.HasIndex("LoadId");

                    b.ToTable("Receipt", (string)null);
                });

            modelBuilder.Entity("ListtleShipManagementSystemDomain.Entities.Ship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CurrentDockId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnTheWay")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ShipAge")
                        .HasColumnType("int");

                    b.Property<int?>("ShipCompanyId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("ShipNationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentDockId");

                    b.HasIndex("ShipCompanyId");

                    b.ToTable("Ship", (string)null);
                });

            modelBuilder.Entity("ListtleShipManagementSystemDomain.Entities.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnTheWay")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Worker", (string)null);
                });

            modelBuilder.Entity("JourneyWorker", b =>
                {
                    b.HasOne("ListtleShipManagementSystemDomain.Entities.Journey", null)
                        .WithMany()
                        .HasForeignKey("JourneysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ListtleShipManagementSystemDomain.Entities.Worker", null)
                        .WithMany()
                        .HasForeignKey("WorkersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ListtleShipManagementSystemDomain.Entities.Captain", b =>
                {
                    b.HasOne("ListtleShipManagementSystemDomain.Entities.Company", "Company")
                        .WithMany("Captains")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ListtleShipManagementSystemDomain.Entities.Company", b =>
                {
                    b.OwnsOne("ListtleShipManagementSystemDomain.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<int>("CompanyId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("HoodName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("No")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CompanyId");

                            b1.ToTable("Company");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("ListtleShipManagementSystemDomain.Entities.Container", b =>
                {
                    b.HasOne("ListtleShipManagementSystemDomain.Entities.Load", "Load")
                        .WithMany("Containers")
                        .HasForeignKey("LoadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Load");
                });

            modelBuilder.Entity("ListtleShipManagementSystemDomain.Entities.Contract", b =>
                {
                    b.HasOne("ListtleShipManagementSystemDomain.Entities.Company", "CustomerCompany")
                        .WithMany("CustomerCompanyContracts")
                        .HasForeignKey("CustomerCompanyId")
                        .IsRequired();

                    b.HasOne("ListtleShipManagementSystemDomain.Entities.Journey", "Journey")
                        .WithOne("Contract")
                        .HasForeignKey("ListtleShipManagementSystemDomain.Entities.Contract", "JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ListtleShipManagementSystemDomain.Entities.Load", "Load")
                        .WithOne("Contract")
                        .HasForeignKey("ListtleShipManagementSystemDomain.Entities.Contract", "LoadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ListtleShipManagementSystemDomain.Entities.Company", "ShipLogisticCompany")
                        .WithMany("ShipCompanyContracts")
                        .HasForeignKey("ShipLogisticCompanyId")
                        .IsRequired();

                    b.OwnsOne("ListtleShipManagementSystemDomain.ValueObjects.Money", "Fee", b1 =>
                        {
                            b1.Property<int>("ContractId")
                                .HasColumnType("int");

                            b1.Property<int>("MoneyAmount")
                                .HasColumnType("int");

                            b1.Property<string>("MoneyNationalityName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ContractId");

                            b1.ToTable("Contract");

                            b1.WithOwner()
                                .HasForeignKey("ContractId");
                        });

                    b.Navigation("CustomerCompany");

                    b.Navigation("Fee")
                        .IsRequired();

                    b.Navigation("Journey");

                    b.Navigation("Load");

                    b.Navigation("ShipLogisticCompany");
                });

            modelBuilder.Entity("ListtleShipManagementSystemDomain.Entities.Dock", b =>
                {
                    b.OwnsOne("ListtleShipManagementSystemDomain.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<int>("DockId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("HoodName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("No")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("DockId");

                            b1.ToTable("Dock");

                            b1.WithOwner()
                                .HasForeignKey("DockId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("ListtleShipManagementSystemDomain.Entities.Journey", b =>
                {
                    b.HasOne("ListtleShipManagementSystemDomain.Entities.Captain", "Captain")
                        .WithMany("Journeys")
                        .HasForeignKey("CaptainId")
                        .IsRequired();

                    b.HasOne("ListtleShipManagementSystemDomain.Entities.Dock", "EndDock")
                        .WithMany("EndJourneyList")
                        .HasForeignKey("EndDockId")
                        .IsRequired();

                    b.HasOne("ListtleShipManagementSystemDomain.Entities.Ship", "Ship")
                        .WithMany("Journeys")
                        .HasForeignKey("ShipId")
                        .IsRequired();

                    b.HasOne("ListtleShipManagementSystemDomain.Entities.Dock", "StartDock")
                        .WithMany("StartJourneyList")
                        .HasForeignKey("StartDockId")
                        .IsRequired();

                    b.Navigation("Captain");

                    b.Navigation("EndDock");

                    b.Navigation("Ship");

                    b.Navigation("StartDock");
                });

            modelBuilder.Entity("ListtleShipManagementSystemDomain.Entities.Receipt", b =>
                {
                    b.HasOne("ListtleShipManagementSystemDomain.Entities.Company", null)
                        .WithMany("ReceiptCustomerCompanyList")
                        .HasForeignKey("CompanyId");

                    b.HasOne("ListtleShipManagementSystemDomain.Entities.Company", null)
                        .WithMany("ReceiptShipCompanyList")
                        .HasForeignKey("CompanyId1");

                    b.HasOne("ListtleShipManagementSystemDomain.Entities.Contract", "Contract")
                        .WithOne("Receipt")
                        .HasForeignKey("ListtleShipManagementSystemDomain.Entities.Receipt", "ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ListtleShipManagementSystemDomain.Entities.Journey", null)
                        .WithMany("Receipts")
                        .HasForeignKey("JourneyId");

                    b.HasOne("ListtleShipManagementSystemDomain.Entities.Load", null)
                        .WithMany("ReceiptList")
                        .HasForeignKey("LoadId");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("ListtleShipManagementSystemDomain.Entities.Ship", b =>
                {
                    b.HasOne("ListtleShipManagementSystemDomain.Entities.Dock", "Dock")
                        .WithMany("Ships")
                        .HasForeignKey("CurrentDockId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ListtleShipManagementSystemDomain.Entities.Company", "ShipCompany")
                        .WithMany("Ships")
                        .HasForeignKey("ShipCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dock");

                    b.Navigation("ShipCompany");
                });

            modelBuilder.Entity("ListtleShipManagementSystemDomain.Entities.Worker", b =>
                {
                    b.HasOne("ListtleShipManagementSystemDomain.Entities.Company", "Company")
                        .WithMany("Workers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ListtleShipManagementSystemDomain.Entities.Captain", b =>
                {
                    b.Navigation("Journeys");
                });

            modelBuilder.Entity("ListtleShipManagementSystemDomain.Entities.Company", b =>
                {
                    b.Navigation("Captains");

                    b.Navigation("CustomerCompanyContracts");

                    b.Navigation("ReceiptCustomerCompanyList");

                    b.Navigation("ReceiptShipCompanyList");

                    b.Navigation("ShipCompanyContracts");

                    b.Navigation("Ships");

                    b.Navigation("Workers");
                });

            modelBuilder.Entity("ListtleShipManagementSystemDomain.Entities.Contract", b =>
                {
                    b.Navigation("Receipt")
                        .IsRequired();
                });

            modelBuilder.Entity("ListtleShipManagementSystemDomain.Entities.Dock", b =>
                {
                    b.Navigation("EndJourneyList");

                    b.Navigation("Ships");

                    b.Navigation("StartJourneyList");
                });

            modelBuilder.Entity("ListtleShipManagementSystemDomain.Entities.Journey", b =>
                {
                    b.Navigation("Contract")
                        .IsRequired();

                    b.Navigation("Receipts");
                });

            modelBuilder.Entity("ListtleShipManagementSystemDomain.Entities.Load", b =>
                {
                    b.Navigation("Containers");

                    b.Navigation("Contract")
                        .IsRequired();

                    b.Navigation("ReceiptList");
                });

            modelBuilder.Entity("ListtleShipManagementSystemDomain.Entities.Ship", b =>
                {
                    b.Navigation("Journeys");
                });
#pragma warning restore 612, 618
        }
    }
}
